### PR TITLE
Add custom margin properties

### PR DESCRIPTION
**Pull request by CodeDoctorDE**
For smaller screens it would be useful to have some margin on the side.
I added small tweaks to add it.

### CODE REVIEW

**Comment by CodeDoctorDE** [comment]
Hi @MattUV can you please look at it?

**Comment by MattUV** [comment]
Hi! I'm sorry I'm not at home at the moment, I'll have more time to look at your pull request next week 😉

**Comment by CodeDoctorDE** [comment]
Hi, do you have any updates?

**Review by MattUV — APPROVED** [review]
Hi!
At first I thought that the variable names would be too close to the original ones (custom_constants/margin_left), but I think it is acceptable.

**Pull request merged**
